nelmio_api_doc:
    documentation:
        info:
            title: Flux Castings
            description: Renvoi toutes les offres présentent sur MegaCastings
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            # Accepts routes under /api except /api/doc and /api/doc.json
            - ^/api(?!/doc)
